models:
  - ampdfm_uncond:checkpoints/dfm/ampdfm_unconditional_epoch200.ckpt
  - ampdfm_cond:checkpoints/dfm/ampdfm_conditional_finetuned.ckpt:generic

data:
  amp_val_path: data/dfm/tokenised_ampdfm_cond/val
  pep_val_path: data/dfm/tokenised_ampdfm_uncond/val

out_dir: outputs/model_comparison
n: 10000
seed: 1234


