# Configuration for antimicrobial activity judge (XGBoost, E. coli only)

task: antimicrobial_activity
model: xgboost

# Data paths
data_dir: /rds/general/user/kja24/home/amp_dfm/data
checkpoint_dir: /rds/general/user/kja24/home/amp_dfm/checkpoints/judges
output_dir: /rds/general/user/kja24/home/amp_dfm/outputs/judges

# Task-specific parameters
organism: "Escherichia coli"

thresholds:
  pos_threshold_ugml: 32
  neg_threshold_ugml: 128
  decision_threshold: 0.5

negatives:
  - negatives_swissprot_with_splits.csv
  - negatives_synth_with_splits.csv

gamma_synthetic: 0.5

# Optuna hyper-parameter tuning
optuna:
  trials: 20
  cv_folds: 5
  search_space:
    max_depth: [3, 8]
    max_leaves: [16, 128]
    learning_rate: [0.003, 0.03]
    subsample: [0.5, 0.9]
    colsample_bytree: [0.5, 0.9]
    min_child_weight: [1.0, 10.0]
    gamma: [0.0, 5.0]
    reg_lambda: [1.0, 10.0]

training:
  num_boost_round: 2000
  early_stopping_rounds: 100

xgboost_params:
  objective: binary:logistic
  eval_metric: auc
  random_state: 42

evaluation:
  cv_folds: 5

