# Configuration for antimicrobial activity judge (XGBoost, all organisms)

task: antimicrobial_activity
model: xgboost

# Data paths
data_dir: /rds/general/user/kja24/home/amp_dfm/data
checkpoint_dir: /rds/general/user/kja24/home/amp_dfm/checkpoints/judges
output_dir: /rds/general/user/kja24/home/amp_dfm/outputs/judges

# Task-specific parameters
organism: null  # null for all organisms, or e.g. "Staphylococcus aureus" for species-specific

thresholds:
  pos_threshold_ugml: 32
  neg_threshold_ugml: 128

negatives:
  - negatives_swissprot_with_splits.csv
  - negatives_synth_with_splits.csv

gamma_synthetic: 0.25  # Down-weight synthetic negatives

# Optuna hyper-parameter tuning
optuna:
  trials: 20
  cv_folds: 5

# Training loop parameters
training:
  num_boost_round: 2000
  early_stopping_rounds: 100

# Optional base XGBoost params (used as defaults before tuning)
xgboost_params:
  objective: binary:logistic
  eval_metric: auc
  random_state: 42

# Evaluation settings
evaluation:
  cv_folds: 5

