# Configuration for haemolysis judge (Logistic Regression)

task: haemolysis
model: logistic_regression

# Data paths
data_dir: /rds/general/user/kja24/home/amp_dfm/data
checkpoint_dir: /rds/general/user/kja24/home/amp_dfm/checkpoints/judges
output_dir: /rds/general/user/kja24/home/amp_dfm/outputs/judges

# Task-specific parameters
thresholds:
  conc_threshold_um: 50
  pct_threshold: 20

# Optuna hyper-parameter tuning
optuna:
  trials: 20
  cv_folds: 5

model_params:
  penalty: l2
  solver: liblinear
  max_iter: 3000
  random_state: 42

evaluation:
  cv_folds: 5

