# Configuration for antimicrobial activity classifier (XGBoost, P. aeruginosa)

task: antimicrobial_activity

# Data paths
data_dir: data
checkpoint_dir: checkpoints/classifiers
output_dir: outputs/classifiers

# Task-specific parameters
organism: "Pseudomonas aeruginosa"

thresholds:
  pos_threshold_ugml: 32
  neg_threshold_ugml: 128
  decision_threshold: 0.5


gamma_synthetic: 0.5

optuna:
  trials: 20
  cv_folds: 5
  search_space:
    max_depth: [3, 8]
    max_leaves: [16, 128]
    learning_rate: [0.003, 0.03]
    subsample: [0.5, 0.9]
    colsample_bytree: [0.5, 0.9]
    min_child_weight: [1.0, 10.0]
    gamma: [0.0, 5.0]
    reg_lambda: [1.0, 10.0]

training:
  num_boost_round: 2000
  early_stopping_rounds: 100

seed: 42
xgboost_params:
  random_state: 42

evaluation:
  cv_folds: 5

