# Configuration for cytotoxicity classifier (XGBoost)

task: cytotoxicity

# Data paths
data_dir: /rds/general/user/kja24/home/amp_dfm/data
checkpoint_dir: /rds/general/user/kja24/home/amp_dfm/checkpoints/classifiers
output_dir: /rds/general/user/kja24/home/amp_dfm/outputs/classifiers

# Task-specific parameters
thresholds:
  tox_threshold_um: 50
  decision_threshold: 0.55

# Optuna hyper-parameter tuning
optuna:
  trials: 20
  cv_folds: 5
  search_space:
    max_depth: [3, 8]
    max_leaves: [16, 128]
    learning_rate: [0.005, 0.05]
    subsample: [0.7, 1.0]
    colsample_bytree: [0.7, 1.0]
    min_child_weight: [1.0, 10.0]
    gamma: [0.0, 5.0]
    reg_lambda: [1.0, 20.0]
    scale_pos_weight: [0.3, 1.5]

training:
  num_boost_round: 2000
  early_stopping_rounds: 100

seed: 42
xgboost_params:
  random_state: 42
  tree_method: hist
  grow_policy: lossguide

evaluation:
  cv_folds: 5

