ckpt: checkpoints/dfm/ampdfm_unconditional_epoch200.ckpt
out_dir: outputs/peptides/generic
run_name: generic_hp4_111_2000

amp_variant: generic
device: cuda:0

n_samples: 2000
n_batches: 10
seq_length: null
len_min: 10
len_max: 30

importance: [1, 1, 1]
homopolymer_gamma: 4.0

