ckpt: /rds/general/user/kja24/home/amp_dfm/checkpoints/dfm/ampdfm_unconditional_epoch200.ckpt
out_dir: /rds/general/user/kja24/home/amp_dfm/outputs/peptides/generic
run_tag: generic_hp4_111_2500

potency_variant: generic
device: cuda:0

n_samples: 2500
n_batches: 10
length: null
len_min: 10
len_max: 30

importance: "1,1,1"
homopolymer_gamma: 4.0

