ckpt: /rds/general/user/kja24/home/amp_dfm/checkpoints/dfm/ampdfm_unconditional_epoch200.ckpt
out_dir: /rds/general/user/kja24/home/amp_dfm/outputs/peptides/ecoli
run_name: ecoli_hp4_111_2000

amp_variant: ecoli
device: cuda:0

n_samples: 2000
n_batches: 10
seq_length: null
len_min: 10
len_max: 30

# Importance weights for classifiers: antimicrobial_activity, haemolysis, cytotoxicity
importance: [1, 1, 1]

# Guidance parameters
homopolymer_gamma: 4.0

# Extra guidance parameters are still accepted via CLI and passed through

